sequenceDiagram
actor Staff
participant System
participant Booking
participant Residencebooking
participant Room
participant DamageItem

Staff->>+System: startRoomInspection(booking_id)

System->>+Booking: get_booking_item(booking_id)
Booking->>+Residencebooking: start_room_check()
Residencebooking->>+Room: update_status("checking")
Room-->>-Residencebooking: status updated
Residencebooking-->>-Booking: room ready
Booking-->>-System: booking detail

System-->>-Staff: inspection started


alt Room Normal
    Staff->>+System: confirmInspectionComplete(booking_id)

    System->>+Booking: update_status("wait_checkout_payment")
    Booking-->>-System: booking updated

    System-->>-Staff: inspection finished


else Room Damaged
    loop For each damage found
        Staff->>+System: addDamage(booking_id, damage_id)

        System->>+Booking: add_damage(damage)
        Booking->>+DamageItem: create damage item
        DamageItem-->>-Booking: damage object
        Booking-->>-System: damage recorded

        System-->>-Staff: damage added
    end

    Staff->>+System: confirmInspectionComplete(booking_id)

    System->>+Booking: update_status("wait_damage_payment")
    Booking-->>-System: booking updated

    System-->>-Staff: inspection finished
end